#!/bin/sh /etc/rc.common
# /etc/init.d/gl-uplink - extender uplink (address, route, relayd). Opal extender only.

START=98
STOP=10
USE_PROCD=1

start_service() {
    grep -q '^UNIT_ROLE=repeater' /etc/gl-mode/unit.conf 2>/dev/null || return 0
    procd_open_instance
    procd_set_param command /usr/bin/gl-uplink.sh
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
