#!/bin/sh /etc/rc.common
# /etc/init.d/modewatch - procd-supervised mode switch watcher

START=99
STOP=10
USE_PROCD=1

start_service() {
    [ -f /etc/gl-mode/switch.conf ] || return 0
    procd_open_instance
    procd_set_param command /usr/bin/gl-mode.sh watch
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
